Vagrant.configure("2") do |config|

  proxy_conf = "proxym300.conf"
  mysql_password = "Aysx1234"

  # Box OS Setting
  config.vm.box = "ubuntu/xenial64"

  # Machine Settings
  config.vm.hostname = "lxwsrv01"

  # Network Settings
  config.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true

  # Folder Sync
  config.vm.synced_folder ".", "/var/www/html/", create: true

  # Provider Settings
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "512" 
  end

  # Shell Commands
  config.vm.provision "shell", inline: <<-SHELL
  # Neuesten Updates holen
   sudo apt-get update
  # Installieren des Webservers, die Firewall und den Proxy
  sudo apt-get install apache2 -y
  sudo apt-get install ufw -y
  
  # Vorkonfiguration für die MYSQL-Installation und deren Installation
  sudo debconf-set-selections <<< "mysql-server mysql-server/root_password password #{mysql_password}"
  sudo debconf-set-selections <<< "mysql-server mysql-server/root_password_again password #{mysql_password}"
  sudo apt-get -yq install mysql-server
  # Vorkonfiguration für die PHPMyAdmin-Installation und deren Installation
  sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/internal/skip-preseed boolean true"
  sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2"
  sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/dbconfig-install boolean false"
  sudo apt-get -yq install phpmyadmin
  
  ## Firewall Regeln und EInstellungen
  sudo ufw deny out to any
  sudo ufw allow from any to any port 22
  sudo ufw allow from any to any port 80
  sudo ufw enable -y
  # Proxymodule aktivieren
  sudo apt-get install libapache2-mod-proxy-html -y
  sudo apt-get install libxml2-dev -y
  sudo a2enmod proxy
  sudo a2enmod proxy_html
  sudo a2enmod proxy_http
  sudo service apache2 restart
  #Proxykonfiguration
  echo "echo '<VirtualHost *:80>' >> /etc/apache2/sites-available/proxy.conf" | sudo bash
  echo "echo '	ServerName mysql-m300' >> /etc/apache2/sites-available/proxy.conf" | sudo bash
  echo "echo '	ServerAlias www.mysql-m300 '>> /etc/apache2/sites-available/proxy.conf" | sudo bash
  echo "echo '	<Location /phpmyadmin/>' >> /etc/apache2/sites-available/proxy.conf" | sudo bash
  echo "echo '		ProxyPreserveHost On' >> /etc/apache2/sites-available/proxy.conf" | sudo bash
  echo "echo '		ProxyPass http://127.0.0.1/phpmyadmin/' >> /etc/apache2/sites-available/proxy.conf" | sudo bash
  echo "echo '		ProxyPassReverse http://127.0.0.1/phpmyadmin/' >> /etc/apache2/sites-available/proxy.conf" | sudo bash
  echo "echo '	</Location>' >> /etc/apache2/sites-available/proxy.conf" | sudo bash
  echo "echo '</VirtualHost>' >> /etc/apache2/sites-available/proxy.conf" | sudo bash
      
  sudo a2ensite /etc/apache2/sites-available/proxy.conf
  #Gruppe Hinzufügen
  groupadd db
  groupadd web
  #Benutzer hinzufügen
  useradd dbuser -p password
  useradd webuser -p password
  #Benutzer der Gruppe hinzufügen
  usermod -aG db dbuser
  usermod -aG web webuser
  #Gruppenordner erstellen
  mkdir -p /grp/db
  mkdir -p /grp/web
  #Gruppenorder Zugriff erstellen
  chmod 770 /grp/db -R
  chown root:db /grp/db/ -R
  chmod 770 /grp/web -R
  chown root:web /grp/web/ -R
  # Apache neustarten
  sudo service apache2 restart
SHELL
end